### ISSUE TITLE
app.min.js not found

### ISSUE THREAD

**Issue by robwent** [dmstr/yii2-adminlte-asset#129]
I'm trying to add this to the basic Yii2 template.

Views are working fine and css is loading, but there is no js.

There is a 404 error for /assets/xxxxx/js/app.min.js

When I check the assets folder the only js file in there is adminlte.min.js and the uncompressed version (And looking again looks like there is demo.js).

Have I made a config error? I have this working fine with the advanced starter template but I can't see any different config values that might stop the js from loading.

**Comment by imitronov** [comment]
I have the same problem with app.min.js on yii2 basic.

**Comment by schmunk42** [comment]
This is looks like a problem of the app template not `yii2-adminlte-asset`. Does app.min.js belong to the app template you are using?

**Comment by imitronov** [comment]
No, app.min.js required with adminlte template only. In folder with app.min.js exists adminlte.js, adminlte.min.js and  demo.js.
Without app.min.js in adminlte don't work right and left menu.

**Comment by imitronov** [comment]
https://github.com/dmstr/yii2-adminlte-asset/blob/master/web/AdminLteAsset.php
18 string

**Comment by schmunk42** [comment]
I see, looks like there have been changes to AdminLTE files in https://github.com/almasaeed2010/AdminLTE/tree/master/dist/js - will fix that tomorrow.

**Comment by robwent** [comment]
Thanks @imitronov 

It looks like they have changed the data attribute for the left sidebar toggle as well.

This: https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/yiisoft/yii2-app/layouts/header.php#L14

needs to be `data-toggle="push-menu"`

**Comment by leealexey** [comment]
Nested menu items don't work too.

**Comment by johnluxor** [comment]
The package almasaeed2010/adminlte has updated to version 2.4 and because of it files in js folder were changed. There is no app.js file. 

To resolve this problem I added depended package as show bellow

```
    "almasaeed2010/adminlte": "~2.3.0",
```

**Comment by schmunk42** [comment]
Fixed in 2.4.4 and 2.5.0-rc1, thank you!

**Comment by robwent** [comment]
I think this is still an issue because of the readme file which installs 2.1

`composer require dmstr/yii2-adminlte-asset "^2.1"`

Anyone following instructions to install from there are going to run into the same issue.

**Comment by schmunk42** [comment]
There might be additional constraints on your side which require an installation of `2.1`. You can use `composer why <package>` to find out more about the constraints.
